plugins:
  cs_discourse_onedrive_enabled:
    default: false
    client: true
  cs_discourse_onedrive_client_id:
    default: ""
    client: true
  cs_discourse_onedrive_tenant_id:
    default: ""
    client: true
  cs_discourse_onedrive_sharepoint_base_url:
    default: ""
    client: true
  cs_discourse_onedrive_sharepoint_site_name:
    default: ""
    client: true
