plugins:
  discourse_cs_onedrive_enabled:
    default: false
    client: true
  discourse_cs_onedrive_client_id:
    default: ""
    client: true
  discourse_cs_onedrive_tenant_id:
    default: ""
    client: true
  discourse_cs_onedrive_sharepoint_base_url:
    default: ""
    client: true
  discourse_cs_onedrive_sharepoint_site_name:
    default: ""
    client: true
